#                **Bases de Python pour le traitement des données**

# Rappels de cours : **Les listes en Python**

## **Objectifs**

Après avoir terminé cette partie, vous serez capable de :

* Effectuer des opérations sur les listes en Python, notamment l’indexation, la manipulation des listes et la copie/le clonage de listes.
* Fonctions vues: `extend`, `append`, `del`, `split`


<a id="index"></a>
## Indexing

Une **liste** est une collection ordonnée de différents objets tels que des entiers, des chaînes de caractères et même d’autres listes.

L’adresse de chaque élément dans une liste est appelée un <b>index</b>. Un index est utilisé pour accéder aux éléments d’une liste et s’y référer.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%202/images/ListsIndex.png" width="1000">

Pour créer une liste, écrivez la liste entre crochets <b>[ ]</b>, avec son contenu à l’intérieur des parenthèses et séparé par des virgules.

In [ ]:
# Créer une liste

L = ["The Bodyguard", 7.0, 1992]
L

On peut ainsi accéder à un élément par son index (**indexing**).

In [ ]:
L = ["The Bodyguard", 7.0, 1992]
L[2]

A noter que l'index peut être **négatif**. L'index -1 pointe vers le dernier élément de la liste, -2 vers l'avant-dernier...

In [ ]:
L[-1]

<a id="content"></a>
## Contenu d'une liste

Les listes peuvent contenir des chaînes de caractères, des nombres flottants et des entiers. Nous pouvons imbriquer d’autres listes, ainsi que des tuples et d’autres structures de données.

In [ ]:
# Example de liste

["The Bodyguard", 7.0, 1992, [1, 2], ("A", 1)]

<a id="op"></a>
## Opérations sur les listes

Nous pouvons effectuer des opérations de découpage (**slicing**) sur les listes. Par exemple, si nous voulons les deux derniers éléments, nous utilisons la commande suivante :

In [ ]:
# Exemple de liste

L = ["The Bodyguard", 7.0,1992,"BG",1]
L

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/KyRT0sxnEHkVDzA5XS6h0w/Slide2.PNG" width="1000">

In [ ]:
# List slicing

L[3:5]

Il est également possible de ne rien préciser à gauche ou à droite du symbole `:`:
* `:2` retourne tous les éléments du début de la liste jusqu'à 2 (exclus)
* `2:` retourne tous les éléments depuis l'indice 2 jusqu'au bout de la liste.

In [ ]:
L[:2]

In [ ]:
L[2:]

A noter que le slicing permet également de **copier** une liste.

Une copie d'une liste peut être modifiée sans que la liste d'origine ne le soit.

In [ ]:
copie_L = L[:]
copie_L[0] = "Hitman"
print(copie_L)
print(L)

Comme les listes sont **mutables**, nous pouvons les modifier.
Note: ceci n'est pas le cas des tuples, qui sont **immutables**.
Par exemple, nous pouvons changer le premier élément comme suit :

In [ ]:
# Change the element based on the index

A = ["disco", 10, 1.2]
print('Avant modification:', A)
A[0] = 'hard rock'
print('Après modification:', A)

Nous pouvons utiliser la méthode `append` pour ajouter un nouvel élément à la liste.

In [ ]:
L = [ "The Bodyguard", 7.0]
L.append('pop')
print(L)
L.append('10')
print(L)
L.append(['carotte', 20])
print(L)

La méthode `append` ajoute chaque élément passé en paramètre à la liste, même si l'élément est une liste.
Nous pouvons utiliser la méthode `extend` pour **concaténer** les listes:

In [ ]:
# Concaténer 2 listes

L = [ "The Bodyguard", 7.0]
L.extend(['pop', 10])
L

Nous pouvons aussi supprimer un élément de la liste en utilisant la fonction `del`:

In [ ]:
# Supprimer un élément à partir de son index

A = ["disco", 10, 1.2]
print('Avant modification:', A)
del(A[0])
print('Après modification:', A)

Nous pouvons convertir une chaîne de caractères en liste en utilisant `split`. Par exemple, la méthode `split` transforme chaque groupe de caractères séparé par un **delimiter** choisi en un élément de la liste :

In [2]:
# Split une chaîne de caractère selon le caractère espace (delimiter)

'hard rock'.split(" ")

['hard', 'rock']

<a id="Exercice"></a>
## **Exercice : la liste de courses**

### Q1.  Créez une liste vide
Commencez par créer une liste vide qui contiendra ensuite tous les éléments de la liste de course.

In [35]:
# Ecrivez votre code ici
lst = []
print(lst)

[]

<details><summary>Cliquez ici pour voir la solution</summary>

```python
Shopping_list=[]

```

</details>

### Q2. Enregistrez les éléments suivants dans la liste de course:
* Montre
* Ordinateur
* Chaussures
* Stylo
* vetements

*Conseil:- Enregistrez chaque élément comme une chaîne de caractère*

In [36]:
# Ecrivez votre code ici
lst.append("Montre")
lst.append("Ordinateur")
lst.append("Chaussures")
lst.append("Stylo")
lst.append("vetements")
print(lst)

['Montre', 'Ordinateur', 'Chaussures', 'Stylo', 'vetements']

<details><summary>Cliquez ici pour voir la solution</summary>

```python
Shopping_list=["Montre","Ordinateur","Chaussures","Stylo","Vêtements"]

# Alternative: la méthode append aurait aussi pu être utilisée

```

</details>

### Q3. Ajoutez un élément manquant à la liste
Il semble qu'on ait oublié de mettre l'élément "**Ballon de Football**" à la liste. Ajoutez-le.
<br>

In [37]:
# Ecrivez votre code ici
lst.append("Ballon de Football")
print(lst)

['Montre', 'Ordinateur', 'Chaussures', 'Stylo', 'vetements', 'Ballon de Football']

<details><summary>Cliquez ici pour voir la solution</summary>

```python
Shopping_list.append("Ballon de Football")

```

</details>

### Q4. Afficher le premier élément de la liste

In [38]:
# Ecrivez votre code ici
print(lst[:1])

['Montre']

<details><summary>Cliquez ici pour voir la solution</summary>

```python
print(Shopping_list[0])

```

</details>

### Q5. Affichez le dernier élément de la liste

In [39]:
# Ecrivez votre code ici
print(lst[-1])

Ballon de Football

<details><summary>Cliquez ici pour voir la solution</summary>

```python
print(Shopping_list[-1])

```

</details>

### Q6. Affichez toute la liste

In [40]:
# Ecrivez votre code ici
print(lst)

['Montre', 'Ordinateur', 'Chaussures', 'Stylo', 'vetements', 'Ballon de Football']

<details><summary>Cliquez ici pour voir la solution</summary>

```python
print(Shopping_list)

```

</details>

### Q7. Affichez les éléments importants à acheter.
En utilisant le slicing, affichez les éléments "Ordinateur" et "Chaussures".

In [42]:
print(lst[1:3])

['Ordinateur', 'Chaussures']

<details><summary>Cliquez ici pour voir la solution</summary>

```python
print(Shopping_list[1:3])

```

</details>

### Q8. Modifiez un élément de la liste
A la place de **Stylo**, nous voulons acheter un **Cahier**. Modifiez la liste en conséquence.

*Conseil:- modifiez la valeur d'un élément de la liste par son index.*

In [45]:
# Ecrivez votre code ici
lst[1] = "PATATE"
print(lst)

['Montre', 'PATATE', 'Stylo', 'vetements', 'Ballon de Football']

<details><summary>Cliquez ici pour voir la solution</summary>

```python
Shopping_list[3] = "Cahier"

```

</details>

### Q9. Supprimez un élément de la liste
Nous ne voulons plus acheter de **Chaussures**, supprimez cet élément de la liste.

In [46]:
# Ecrivez votre code ici
del(lst[2])
print(lst)

['Montre', 'PATATE', 'vetements', 'Ballon de Football']

<details><summary>Cliquez ici pour voir la solution</summary>

```python
del (Shopping_list[4])

```

</details>

### Q10. Agréger des listes
Vos parents vous demande de faire leurs courses en même temps que les votres.
Ils vous donnent leur liste de course qui contient: Oeuf, lait et farine.

Créez une nouvelle liste de course contenant ce que vos parents ont besoin d'acheter. Concaténez cette liste à la votre. Affichez la liste finale.

In [49]:
# Ecrivez votre code ici
lst2 = ["Patate", "Poney"]
lst.extend(lst2)
print(lst)

['Montre', 'PATATE', 'vetements', 'Ballon de Football', ['Patate', 'Poney'], 'Patate', 'Poney']

<details><summary>Cliquez ici pour voir la solution</summary>

```python
shopping_list_parents = ["oeuf","lait","farine"]
Shopping_list.extend(shopping_list_parents)
print(Shopping_list)

```

</details>

# <hr>

# Rappels de cours: **Les dictionnaires en Python**


## **Objectifs**

Après avoir terminé cette partie, vous serez capable de :

* Créer un dictionnaire et effectuer des opérations sur celui-ci

<a id="content"></a>
## Qu'est-ce qu'un dictionnaire ?

Un dictionnaire est une structure de données qui se compose de **clés** et de **valeurs**. Ces clés permettent d’accéder aux valeurs contenues dans le dictionnaire.

Dans une liste, les éléments sont indexés par un nombre entier, alors que dans un dictionnaire l'indexe est une clé, qui peut être de n'importe quel type (où plus précisément de tout type immutable, comme un entier, une string, un tuple ...).

Le meilleur exemple d’un dictionnaire est l’accès aux informations d’une personne à l’aide du **numéro de sécurité sociale**.
Ici, le numéro de sécurité sociale, qui est unique, sera la **clé**, et les informations de la personne seront les **valeurs** qui y sont associées.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/54cVKVMZaWEw7wSCDL8NjQ/DictList1.png" width="650">

## Créer un Dictionaire et accéder aux éléments

Ici, nous créons un dictionnaire nommé **Dict** avec les détails suivants :

* Les clés sont **"key1", "key2", "key3", "key4", "key5" et (0,1)**.
* Les valeurs sont 1, 2, [3, 3, 3], (4, 4, 4), 5 et 6.

In [ ]:
# Créer un dictionaire

Dict = {"key1": 1, "key2": "2", "key3": [3, 3, 3], "key4": (4, 4, 4), 'key5': 5, (0, 1): 6}
Dict

Les clés peuvent être des chaînes de caractères :

In [ ]:
# Accéder à une valeur par sa clé

Dict["key1"]

Les clés peuvent aussi être de tout type immutable, comme un tuple :

In [ ]:
# Accéder à une valeur par sa clé

Dict[(0, 1)]

Chaque clé est séparée de sa valeur par deux-points "<code>:</code>". Les éléments sont séparés par des virgules, et l’ensemble du dictionnaire est encadré par des accolades. Un dictionnaire vide, sans aucun élément, s’écrit simplement avec deux accolades, comme ceci : "<code>{}</code>".

In [ ]:
# Créer

release_year_dict = {"Thriller": "1982", "Back in Black": "1980", \
                    "The Dark Side of the Moon": "1973", "The Bodyguard": "1992", \
                    "Bat Out of Hell": "1977", "Their Greatest Hits (1971-1975)": "1976", \
                    "Saturday Night Fever": "1977", "Rumours": "1977"}
release_year_dict

En résumé, comme une liste, un dictionnaire contient une séquence d’éléments. Chaque élément est représenté par une **clé** et sa **valeur** correspondante. **Pour chaque clé, il ne peut y avoir qu’une seule valeur**, mais plusieurs clés peuvent partager la même valeur. Les clés ne peuvent être que des chaînes de caractères, des nombres ou des tuples, tandis que les valeurs peuvent être de n’importe quel type de données.

Il est utile de visualiser le dictionnaire comme un tableau, comme dans l’image suivante. La première colonne représente les **clés**, et la deuxième colonne représente les **valeurs**.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%202/images/DictsStructure.png" width="650">

<a id="cles"></a>
## Clés

On peut accéder aux valeurs d'un dictionnaire par leur clé :

In [ ]:
# Récupérer une valeur par sa clé

release_year_dict['Thriller']

Cela correspond à :

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%202/images/DictsKeyOne.png" width="500">

On peut **modifier la valeur** correspondant à une clé :

In [ ]:
# Modifier la valeur correspondant à une clé
release_year_dict['Thriller'] = "1983"
release_year_dict

Dans le cas où la clé n'existe pas dans l'exemple précédent, la **paire clé valeur est ajoutée** au dictionnaire :

In [ ]:
# Ajouter une paire clé/valeur au dictionnaire ('Graduation' n'est pas une clé du dictionnaire)

release_year_dict['Graduation'] = '2007'
release_year_dict

On peut **supprimer** un élément du dictionnaire avec la fonction `del` :

In [ ]:
# Delete entries by key

del(release_year_dict['Thriller'])
del(release_year_dict['Graduation'])
release_year_dict

Enfin, on peut vérifier qu'un élément une clé du dictionnaire avec l'opérateur `in` :

In [ ]:
# Vérifie si la clé est dans le dictionnaire

'The Bodyguard' in release_year_dict

<a id="dict-boucle"></a>
## Dictionnaire et boucles

On peut récupérer toutes les clés d'un dictionnaire avec la méthode <code>keys()</code>:

In [ ]:
# Récupérer toutes les clés

release_year_dict.keys()

Utilisée dans une boucle, cette méthode nous permet de parcourir tous les éléments d'un dictionnaire :

In [ ]:
# Afficher toutes les paires d'un dictionnaire
for k in release_year_dict.keys():
  print(k,"-",release_year_dict[k])

On peut également récupérer toutes les valeurs d'un dictionnaire avec la méthode `values()`.

A noter qu'il n'est pas possible de retrouver la clé à partir d'une valeur, car plusieurs clés différentes peuvent correspondre à la même valeur.

In [ ]:
# Get all the values in dictionary

release_year_dict.values()

Enfin on peut récupérer toutes les paires avec la méthode `items()`:

In [ ]:
release_year_dict.items()

In [ ]:
for k,v in release_year_dict.items():
  print(k,"-",v)

<hr>

<a id="Scenario"></a>
## **Exercice : gestion des stocks d'un magasin**

Cet exercice vise à utiliser des dictionnaires pour représenter les stocks d'un magasin.

### Q1. Créer un dictionnaire vide

Créer un premier dictionnaire vide où vous stockerez les informations du premier produit.

In [3]:
#Ecrivez votre code ici
dic = {
  1: "one",
  2: "two"
}

print(dic)

{1: 'one', 2: 'two'}

<details> <summary>Cliquez ici pour voir la solution</summary>

```python

produit1 ={}

```

</details>

### Q2 Enregistrez les valeurs du premier produit

Remplissez le dictionnaire précédemment créé avec les paires clé-valeur suivantes :
* "Nom"= "Téléphone portable"
* "Quantite"= 5
* "Prix"= 20000
* "Année"= 2020

In [8]:
#Ecrivez votre code ici
dic["Nom"] = "Téléphone portable"
dic["Quantite"] = 5
dic["Prix"] = 20000
dic["Année"] = 2020
print(dic)

{1: 'one', 2: 'two', 'Nom': 'Téléphone portable', 'Quantite': 5, 'Prix': 20000, 'Année': 2020}

<details> <summary>Cliquez ici pour voir la solution</summary>

```python
produit1["Nom"]= "Téléphone portable"
produit1["Quantite"]= 5
produit1["Prix"]= 20000
produit1["Année"]=2020
```
</details>

### Q3. Modifiez un dictionnaire

En faisant l'inventaire de votre magasin, vous retrouvez 10 téléphone portables (produit1) supplémentaires.

Modifiez le dictionnaire précédent pour ajouter 10 à la quantité existante. Et affichez le dictionnaire resultant.

In [20]:
#Ecrivez votre code ici
dic["Quantite"] = dic["Quantite"] + 10
print(dic)

{1: 'one', 2: 'two', 'Nom': 'Téléphone portable', 'Quantite': 120, 'Prix': 20000, 'Année': 2020}

<details> <summary>Click here for the solution</summary>

```python

produit1["Quantite"] = produit1["Quantite"]+10
produit1
```

</details>

### Q4. Créer une second dictionnaire pour le second produit.

Créez un second dictionnaire qui contient les informations du second produit:
* "Nom"= "Ordinateur protable"
* "Quantite"= 10
* "Prix" = 50000
* "Année"= 2023

In [21]:
#Ecrivez votre code ici
dic2 = { "Nom" : "Ordinateur portable", "Quantite" : 5, "Prix" :20000, "Année" : 2020 }
print(dic2)

{'Nom': 'Ordinateur portable', 'Quantite': 5, 'Prix': 20000, 'Année': 2020}

<details> <summary>Cliquez ici pour voir la solution</summary>

```python

product2 = {"Nom":"Ordinateur protable", "Quantite":10,"Prix":50000,"Année":2023}

```

</details>

### Q5. Créer un dictionnaire pour l'inventaire

Créez un troisième dictionnaire pour l'inventaire. Il contient les 2 produits définis précédemment. Utilisez le nom du produit comme clé dans le dictionnaire d'inventaire.
Affichez le nouveau dictionnaire.

In [23]:
#Ecrivez votre code ici
inventory = {
  1: dic,
  2: dic2
}
print(inventory)

{1: {1: 'one', 2: 'two', 'Nom': 'Téléphone portable', 'Quantite': 120, 'Prix': 20000, 'Année': 2020}, 2: {'Nom': 'Ordinateur portable', 'Quantite': 5, 'Prix': 20000, 'Année': 2020}}

<details> <summary>Cliquez ici pour voir la solution</summary>

```python

inventory= {"Téléphone portable":produit1,"Ordinateur protable":product2}
inventory

```

</details>

### Q6. Affichez le noms des produits présents l'inventaire

Vous pouvez afficher les clés du dictionnaire représentant l'inventaire ou le nom de chacun des produits de l'inventaire.

In [ ]:
#Ecrivez votre code ici

<details> <summary>Cliquez ici pour voir la solution</summary>

```python

print(inventory.keys())

# Autre possibilité
for k in inventory:
  print(k)

# Autre possibilité
for k in inventory:
  print(inventory[k]["Nom"])

```

</details>

### Q7. Vérifier que des produits sont dans l'inventaire

Vérifiez qu'un produit identifié par la clé "Téléphone portable" est présent dans le dictionnaire.
De même, vérifiez qu'il n'y a pas de produit identifié par la clé "Smartphone" dans l'inventaire.

In [ ]:
#Ecrivez votre code ici
# for k,v in inventory.items():
  # print(v.Nom = "Téléphone portable")

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (3071643186.py, line 3)

<details> <summary>Cliquez ici pour voir la solution</summary>

```python

print("Téléphone portable" in inventory)
print("Smartphone" not in inventory)

```

</details>

### Q8. Parcourir un dictionnaire

A partir du dictionnaire représentant l'inventaire, calculer le nombre total d'articles présents dans le magasin.

*Conseil: cela revient à faire la somme des quantité de chacun des articles du magasin*

In [ ]:
#Ecrivez votre code ici

<details> <summary>Cliquez ici pour voir la solution</summary>

```python

s = 0
for article in inventory.values():
  s += article["Quantite"]
print(s)

```

</details>

### Q9. Supprimer un élément de l'inventaire

Vous venez de vendre tout votre stock de téléphones portables. Supprimez ce produit de l'inventaire.

In [ ]:
#Ecrivez votre code ici


<details> <summary>Cliquez ici pour voir la solution</summary>

```python

del(inventory["Téléphone portable"])
inventory

```

</details>

# <hr>

# Introduction à Numpy par la pratique : **Tableaux 1D en Numpy**

## **Objectifs**

Après avoir terminé cette partie, vous serez capable de :

* Importer et utiliser la bibliothèque `numpy`
* Effectuer des opérations avec `numpy`

## Qu'est-ce que Numpy?

NumPy est une bibliothèque Python utilisée pour travailler avec des **tableaux** (à 1 ou n dimensions) et de réaliser des opérations d’**algèbre linéaire**... NumPy signifie *Numerical Python* et c’est un projet open source. L’objet tableau dans NumPy s’appelle **ndarray** et il fournit de nombreuses fonctions qui facilitent grandement le travail avec les ndarrays.

Les tableaux sont très fréquemment utilisés en **science des données**, où la vitesse et les ressources sont très importantes.

Numpy permet de réaliser des opérations vectorielles : par exemple, il est possible de faire une addition sur 2 tableaux (avec l'opérateur `+`). Sans la librairy Numpy, il es nécessaire de faire une boucle pour additionner deux listes. **Les opérations vectorielles (sur les tableaux) sont beaucoup plus rapide que l'utilisation de boucles.**

La taille des tableaux est généralement fixe et chaque élément est du même type. Nous pouvons convertir une liste en tableau NumPy en important d’abord `numpy` :

In [ ]:
# Importer la librairie numpy
# NumPy est généralement importé sous l’alias np.

import numpy as np

On peut transformer une liste en un tableau Numpy avec :

In [ ]:
# Créer un tanleau Numpy

a = np.array([0, 1, 2, 3, 4])
a

Chaque élément du tableau est du même type que dans la liste, ici entier :

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumOneNp.png" width="500">

### Indexing

Comme pour les listes, on peut accéder à chaque élément par son indexe en utilisant la notation avec crochets:

In [ ]:
# Afficher chaque élément

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

### Type

Le type d'un tableau Numpy est `numpy.ndarray`:

In [ ]:
# Vérifier le type d'un tableau

type(a)

Comme les tableaux NumPy contiennent des données du même type, nous pouvons utiliser l’attribut **`dtype`** pour obtenir le type de données des éléments du tableau. Dans ce cas, il s’agit d’un entier 64 bits :

In [ ]:
# Vérifier le type des valeurs du tableau

a.dtype

#### Exercice

Quel est le type de la variable `b` ci-dessous et de ses éléments ?

In [ ]:
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])

# Ecrivez votre code ici

<details><summary>Cliquez ici pour voir la solution</summary>

```python
type(b)
    
b.dtype
    
```

</details>

### Modifier un tableau

Il est possible de modifier une valeur d'un tableau en utilisant son index.

Soit le tableau `c` suivant :

In [ ]:
# Créer un nouveau tableau

c = np.array([20, 1, 2, 3, 4])
c

On peut modifier la valeur du premier élément avec :

In [ ]:
# Affecter la valeur 100 au premier élément du tableau

c[0] = 100
c

#### Exercice

Affecter la valeur 20 au deuxième élément du tableau ci-dessous :

In [ ]:
a = np.array([10, 2, 30, 40,50])

# Ecrivez votre code ici

<details><summary>Cliquez ici pour voir la solution</summary>

```python
a[1]=20
a
   
```

</details>

### Slicing

Comme pour les listes, nous pouvons effectuer des opérations de découpage (*slicing*) sur les tableaux NumPy. Le découpage en Python consiste à extraire des éléments compris entre un index de départ et un index de fin donné.

Nous passons le découpage de la manière suivante : `[start:end]`. L’élément à l’index de fin n’est **pas inclus** dans le résultat.

Nous pouvons sélectionner les éléments de 1 à 3 et les affecter à un nouveau tableau NumPy <code>d</code> comme suit :

In [ ]:
# Slicing le tableau Numpy

d = c[1:4]
d

On peut assigner des nouvelles valeur aux indexes précisés dans le slicing :

In [ ]:
# Assigne au 4eme et 5eme éléments les valeurs 300 et 400

c[3:5] = 300, 400
c

On peut aussi définir un pas dans le découpage avec : `[start:end:step]`.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

Si *start* n'est pas précisé, sa valeur par défaut est 0.

In [ ]:
print(arr[:4])

Si *end* n'est pas précisé, sa valeur par défaut est la taille du tableau.

In [ ]:
print(arr[4:])

Si *step* n'est pas précisé, sa valeur par défaut est 1.

In [ ]:
print(arr[1:5:])

#### Exercice

Afficher les éléments avec un indice impair dans le tableau ci-dessous.

In [28]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Ecrivez votre code ici

NameError: name 'np' is not defined

<details><summary>Cliquez ici pour voir la solution</summary>

```python
print(arr[1:8:2])

# ou
print(arr[1::2])
    
```

</details>

### Indexing et modification à partir d'une liste d'indexes

De la même manière, nous pouvons utiliser une liste pour sélectionner plusieurs index spécifiques.

La liste `select` contient plusieurs valeurs :

In [ ]:
# Création d'une liste d'indexes

select = [0, 2, 3, 4]
select

Nous pouvons utiliser la liste comme argument entre les crochets. Le résultat correspond aux éléments situés aux indexes indiqués :

In [ ]:
# Utiliser la liste pour sélectionner des elements

d = c[select]
d

Nous pouvons affecter une nouvelle valeur aux éléments spécifiés. Par exemple, nous pouvons leur attribuer la valeur **100 000** comme suit :

In [ ]:
# Affecter une valeur à tous les éléments dont l'indice est dans select

c[select] = 100000
c

### Autres attributs des tableaux Numpy

Soit le tableau suivant :

In [ ]:
# Création d'un tableau Numpy

a = np.array([0, 1, 2, 3, 4])
a

L'attribut <code>size</code> contient le nombre d'éléments du tableau :

In [ ]:
# Taille du tableau

a.size

Les deux attributs suivants prendront davantage de sens lorsque nous aborderons les tableaux en dimensions supérieures, mais examinons-les dès maintenant.

L’attribut `ndim` représente le nombre de dimensions du tableau, ou le rang du tableau. Dans ce cas, il est égal à 1 :

In [ ]:
# Nombre de dimensions du tableau

a.ndim

L’attribut `shape` est un tuple d’entiers indiquant la taille du tableau dans chaque dimension :

In [ ]:
# Shape du tableau

a.shape

#### Exercice

Trouver la taille, le nombre de dimensions et la *shape* du tableau `b` ci-dessous :

In [ ]:
b = np.array([10, 20, 30, 40, 50, 60, 70])

# Ecrivez votre code ici

<details><summary>Cliquez ici pour voir la solution</summary>

```python
b.size

b.ndim

b.shape
    
```

</details>

### Fonctions statistiques en Numpy

Numpy propose des méthodes sur les tableaux permettant de calculer la moyenne (`mean()`), l'écart-type (`std()`), le maximum (`max()`), le minimum (`min()`) ou la somme des éléments d'un tableau (`sum()`).

In [ ]:
# Création d'un nouveau tableau

a = np.array([1, -1, 1, -1])

In [ ]:
# Moyenne du tableau

m = a.mean()
m

In [ ]:
# Ecart-type d'un tableau

standard_deviation=a.std()
standard_deviation

In [ ]:
# Création d'un nouveau tableau

b = np.array([-1, 2, 3, 4, 5])
b

In [ ]:
# Maximum d'un tableau

max_b = b.max()
max_b

In [ ]:
# Minimum d'un tableau

min_b = b.min()
min_b

In [ ]:
# Somme des éléments d'un tableau

sum_b = b.sum()
sum_b

#### Exercice

Trouver la somme des valeurs minimales et maximales du tableau `c` ci-dessous :

In [ ]:
c = np.array([-10, 201, 43, 94, 502])

# Ecrivez votre code ici

<details><summary>Cliquez ici pour voir la solution</summary>

```python
max_c = c.max()
max_c
    
min_c = c.min()
min_c
       
Sum = (max_c +min_c)
Sum
```

</details>

<hr>

## Opérations sur les tableaux

### Opérations de base

Les opérations arithmétiques de base (`+`,`-`,`*`,`/`) sont définies sur les tableaux : l'opération est effectuée terme à terme.

Attention : les tableaux doivent être de même taille.

In [ ]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

Les opérations arithmétiques de base (`+`,`-`,`*`,`/`) ont également été définies **entre un tableau et un scalaire** : on peut par exemple additionner un nombre à chaque élément d'un tableau .

In [ ]:
arr1 = np.array([10, 11, 12, 13, 14, 15])

print(arr1 + 10)
print(arr1 - 2)
print(arr1 * 2)
print(arr1 / 10)

#### Exercice

Pour chaque étudiant, on définit un tableau de notes: [Note de programmation, Note d'anglais, Note de base de données] (par exemple [18.0,9.5,14.0]).

On considère une classe de 3 étudiants, dont les notes sont les suivantes : [18.0,9.5,14.0], [8.0,19.5,4.0] et [18.0,19.5,14.0].

Définir 3 tableaux Numpy pour stocker ces valeurs. Puis calculer le tableau contenant la moyenne de la classe en programmation, anglais et base de données.

In [ ]:
# Ecrivez votre code ici

<details><summary>Cliquez ici pour voir la solution</summary>

```python
etu1 = np.array([18.0,9.5,14.0])
etu2 = np.array([8.0,19.5,4.0])
etu3 = np.array([18.0,19.5,14.0])

som = etu1+etu2+etu2
print(som)
moy = som/3
print(moy)
    
```

</details>

### Fonctions Numpy

Numpy propose également des fonctions permettant de réalisant les différentes opérations arithmétiques de base :
* `np.add(arr1,arr2)`
* `np.subtract(arr1, arr2)`
* `np.multiply(arr1, arr2)`
* `np.divide(arr1, arr2)`

In [ ]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

addi = np.add(arr1,arr2)
print(addi)
sub = np.subtract(arr1, arr2)
print(sub)
mult = np.multiply(arr1, arr2)
print(mult)
div = np.divide(arr1, arr2)
print(div)

Les fonctions Numpy (ex. `np.add()`) sont équivalentes aux opérateurs de bases (ex. `+`) dans beaucoup de cas.

Néanmoins les fonctions Numpy permettent des options supplémentaires comme:
* `where` permet de n'effectuer l'opération que lorsque la condition est vérifiée. Pour les autres éléments, la valeur n'est pas définie
* `out` spécifie dans quel tableau le résultat est placé, sans avoir à le créer.

Ces options permettent d'optimiser des gros calculs.

In [ ]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

r = np.zeros_like(arr1)
np.add(arr1,arr2,out=r,where=arr1 > 13)

#### Exercice

Soient 2 tableaux : arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25]).

En utilisant les fonctions Numpy,
* calculez un nouveau tableau arr3 contenant la différence entre arr1 et arr2,
* calculez nu nouveau tableau arr4 contenant le carré de arr3 (c'est-à-dire multipliez arr3 par lui-même),
* calculez la somme des éléments de arr4 et prenez la racine carrée du résultat.

Félicitations vous venez de calculez la distance entre les deux vecteurs arr1 et arr2.

In [ ]:
from math import sqrt

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

# Ecrivez votre code ici

<details><summary>Cliquez ici pour voir la solution</summary>

```python
arr3 = np.subtract(arr1,arr2)
arr4 = np.multiply(arr3,arr3)
s = arr4.sum()
distance = sqrt(s)
distance
    
```

</details>

### Produit scalaire

Le produit scalaire prend 2 tableaux en paramètres et renvoie un nombre (un scalaire). Il est réalisé en utilisant la fonction `np.dot` :

In [ ]:
X = np.array([1, 2])
Y = np.array([3, 2])

In [ ]:
# Calcul du produit scalaire
np.dot(X, Y)

In [ ]:
#Elements de X
print(X[0])
print(X[1])

In [ ]:
#Elements de Y
print(Y[0])
print(Y[1])

Nous effectuons le produit scalaire, comme illustré ci-dessous :

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/dot1.png">

#### Exercice

Réaliser le produit scalaire des 2 tableaux suivants :

In [ ]:
arr1 = np.array([3, 5])
arr2 = np.array([2, 4])

# Ecrivez votre code ici

<details><summary>Cliquez ici pour voir la solution</summary>

```python
arr3 = np.dot(arr1, arr2)
arr3

    
```

</details>

<hr>

## Fonctions mathématiques

On peut accéder à la valeur de `pi` comme suit :

In [ ]:
# The value of pi
np.pi

Nous pouvons créer le tableau NumPy suivant en **radians** :

In [ ]:
# Création d'un tableau Numpy en radian

x = np.array([0, np.pi/2 , np.pi])

Nous pouvons appliquer la fonction `sin` au tableau `x` et affecter les résultats au tableau `y` ; cela applique la fonction sinus à chaque élément du tableau :

In [ ]:
# Calcul du sinus de chaque élément

y = np.sin(x)
y

<hr>

## Itérer sur des tableaux 1-D

Itérer signifie parcourir chaque élément un par un.

Il est possible d'itérer sur un tableau Numpy en 1-dimension de la même manière que sur une liste.

In [ ]:
arr1 = np.array([1, 2, 3])
print(arr1)

for x in arr1:
  print(x)

## Quiz sur les tableaux Numpy à 1-dimension

Ecrire la soustraction entre les 2 vecteurs Numpy `u` et `v` ci-dessous :

In [ ]:
u = np.array([1, 0])
v = np.array([0, 1])

# Ecrivez votre code ici

<details><summary>Cliquez ici pour voir la solution</summary>

```python
u - v
```

</details>

<hr>

Multipliez le tableau `z`ci-dessous par -2:

In [ ]:
z = np.array([2, 4])

# Ecrivez votre code ici

<details><summary>Cliquez ici pour voir la solution</summary>

```python
-2 * z
```

</details>

<hr>

Soient les listes `[1, 2, 3, 4, 5]` et `[1, 0, 1, 0, 1]`. Transformez ces deux listes en tableaux et multipliez les:

In [ ]:
# Ecrivez votre code ici

<details><summary>Cliquez ici pour voir la solution</summary>

```python
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 0, 1, 0, 1])
a * b
```

</details>

<hr>

Convertir les listes <code>\[-1, 1]</code> et <code>\[1, 1]</code> en tableaux Numpy <code>a</code> et <code>b</code>. Ensuite, tracez ces deux tableaux en utilisant la fonction <code>Plotvec2</code> et calculer leur produit scalaire :

In [ ]:
import matplotlib.pyplot as plt

# Cette fonction trace des deux tableaux/vecteur a et b :
def Plotvec2(a,b):
    ax = plt.axes()
    ax.arrow(0, 0, *a, head_width=0.05, color ='r', head_length=0.1)
    plt.text(*(a + 0.1), 'a')
    ax.arrow(0, 0, *b, head_width=0.05, color ='b', head_length=0.1)
    plt.text(*(b + 0.1), 'b')
    plt.ylim(-2, 2)
    plt.xlim(-2, 2)

# Ecrivez votre code ici

<details><summary>Cliquez ici pour voir la solution</summary>

```python
import matplotlib.pyplot as plt

def Plotvec2(a,b):
    ax = plt.axes()
    ax.arrow(0, 0, *a, head_width=0.05, color ='r', head_length=0.1)
    plt.text(*(a + 0.1), 'a')
    ax.arrow(0, 0, *b, head_width=0.05, color ='b', head_length=0.1)
    plt.text(*(b + 0.1), 'b')
    plt.ylim(-2, 2)
    plt.xlim(-2, 2)

a = np.array([-1, 1])
b = np.array([1, 1])
Plotvec2(a, b)
print("The dot product is", np.dot(a,b))

```

</details>

<hr>

Faites de même avec les listes  <code>\[1, 0]</code> and <code>\[0, 1]</code>.

In [ ]:
import matplotlib.pyplot as plt

# Cette fonction trace des deux tableaux/vecteur a et b :
def Plotvec2(a,b):
    ax = plt.axes()
    ax.arrow(0, 0, *a, head_width=0.05, color ='r', head_length=0.1)
    plt.text(*(a + 0.1), 'a')
    ax.arrow(0, 0, *b, head_width=0.05, color ='b', head_length=0.1)
    plt.text(*(b + 0.1), 'b')
    plt.ylim(-2, 2)
    plt.xlim(-2, 2)


# Ecrivez votre code ici

<details><summary>Cliquez ici pour voir la solution</summary>

```python
import matplotlib.pyplot as plt

# Cette fonction trace des deux tableaux/vecteur a et b :
def Plotvec2(a,b):
    ax = plt.axes()
    ax.arrow(0, 0, *a, head_width=0.05, color ='r', head_length=0.1)
    plt.text(*(a + 0.1), 'a')
    ax.arrow(0, 0, *b, head_width=0.05, color ='b', head_length=0.1)
    plt.text(*(b + 0.1), 'b')
    plt.ylim(-2, 2)
    plt.xlim(-2, 2)


# Ecrivez votre code ici
a = np.array([1, 0])
b = np.array([0, 1])
Plotvec2(a, b)
print("The dot product is", np.dot(a, b))
```

</details>

<hr>

Convertissez les listes `[1, 2, 3]` et `[8, 9, 10]` en tableaux NumPy `arr1` et `arr2`. Ensuite, effectuez l’Addition, la Soustraction, la Multiplication, la Division et le produit scalaire de ces 2 tableaux.

In [ ]:
# Ecrivez votre code ici

<details><summary>Cliquez ici pour voir la solution</summary>

```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([8, 9, 10])

arr3 = np.add(arr1, arr2)
arr3

arr4 = np.subtract(arr1, arr2)
arr4

arr5 = np.multiply(arr1, arr2)
arr5


arr6 = np.divide(arr1, arr2)
arr6

arr7 = np.dot(arr1, arr2)
arr7
```

</details>

Convertissez les listes <code>[1, 2, 3, 4, 5]</code> et <code>[6, 7, 8, 9, 10]</code> en tableaux NumPy <code>arr1</code> et <code>arr2</code>. Ensuite, affichez les nombres pairs et impairs dans <code>arr1</code> et <code>arr2</code> en utilisant les fonctions de slicing.

In [ ]:
# Ecrivez votre code ici

<details><summary>Cliquez ici pour voir la solution</summary>

```python
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

even_arr1 = arr1[1:5:2]
print("Pairs pour array1",even_arr1)
    
odd_arr1=arr1[0:5:2]
print("Impairs pour array1",odd_arr1)

even_arr2 = arr2[0:5:2]
print("Pairs pour array2",even_arr2)
    
odd_arr2=arr2[1:5:2]
print("Impairs pour array2",odd_arr2)

```

</details>

# <hr>

# Introduction à Numpy par la pratique : **Tableaux 2D en Numpy**

## **Objectifs**

Après avoir terminé cette partie, vous serez capable de :

* Manipuler efficacement la bibliothèque `numpy`
* Effectuer des opérations complexes avec `numpy` sur des tableaux à 2-dimensions

## Créer un tableau à 2 dimensions

In [ ]:
# Importer la library

import numpy as np

Considérons la liste <code>a</code>, qui contient trois listes imbriquées **chacune de taille égale**.

In [ ]:
# Création de la liste

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

On peut la transfomer en un tableau Numpy:

In [ ]:
# Convertir la liste en tableau Numpy

A = np.array(a)
A

Nous pouvons utiliser l’attribut <code>ndim</code> pour obtenir le nombre d’axes ou de dimensions, appelé également le rang.

In [ ]:
# Afficher le nombre de dimensions du tableau

A.ndim

L'attribut <code>shape</code> renvoie un tuple contenant la taille du tableau dans chaque dimension.

In [ ]:
A.shape

Le nombre total d'éléments du tableaux est accessible par l'attirbut `size`.

In [ ]:
A.size

<hr>

## Accéder aux différents éléments du tableau

Nous pouvons utiliser des crochets pour accéder aux différents éléments du tableau. La correspondance entre les crochets, la liste et la représentation rectangulaire est illustrée dans la figure suivante pour un tableau 3x3 :

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoEg.png" width="500">

Nous pouvons accéder à l’élément de la 2ᵉ ligne et de la 3ᵉ colonne, comme illustré dans la figure suivante :

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFT.png" width="400">

In [ ]:
# Accès à l'élément de la deuxième ligne et troisième colonne

A[1, 2]

On peut aussi utiliser la notation suivante qui est équivalente :

In [ ]:
# Accès à l'élément de la deuxième ligne et troisième colonne

A[1][2]

Nous pouvons également utiliser le découpage (*slicing*) dans les tableaux NumPy.
Considérons la figure suivante. Nous souhaitons obtenir les **deux premières colonnes de la première ligne**.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoFSF.png" width="400">

Cela peut être réalisé avec la syntaxe suivante :

In [ ]:
A[0][0:2]

De même, on peut obtenir les deux premières lignes de la troisième colonne:

In [ ]:
A[0:2, 2]

Corresponding to the following figure:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/2D_numpy.png" width="400"><br />

Il existe également le raccourci suivant pour récupérer les valeurs de toutes les colonnes étant donné une ou plusieurs lignes choisies

In [ ]:
# Renvoyer la troisième ligne
A[2,]

### Exercice

Affichez les 2 dernières colonnes des 2 dernières lignes du tableau `A` précédent.

In [ ]:
# Ecrivez votre code ci-dessous

<details><summary>Cliquez ici pour voir la solution</summary>

```python
A[0:2,0:2]
```

</details>

## Opérations de base

Nous pouvons également additionner des tableaux à 2-dimensions. Le processus est identique à l’addition de matrices. L’addition des matrices <code>X</code> et <code>Y</code> est illustrée dans la figure suivante :

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoAdd.png" width="500">

In [ ]:
# Création du tableau X

X = np.array([[1, 0], [0, 1]])
X

In [ ]:
# Création du tableau Y

Y = np.array([[2, 1], [1, 2]])
Y

On peut addition les 2 tableaux comme suit :

In [ ]:
# Addition de X et Y

Z = X + Y
Z

Multiplier un tableau NumPy par un **scalaire** est identique à multiplier une matrice par un scalaire.
Si nous multiplions la matrice <code>Y</code> par le scalaire 2, nous multiplions simplement chaque élément de la matrice par 2, comme illustré dans la figure.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoDb.png" width="500">

On réalise cette opération en Numpy comme suit :

In [ ]:
# Création du tableau Y

Y = np.array([[2, 1], [1, 2]])
Y

In [ ]:
# Multiplication de Y par 2

Z = 2 * Y
Z

La multiplication de deux tableaux correspond à un produit élément par élément ou <em>produit de Hadamard</em>.
Considérons les matrices <code>X</code> et <code>Y</code>. Le produit de Hadamard consiste à multiplier **chaque élément situé à la même position**, c’est-à-dire à multiplier ensemble les éléments contenus dans les mêmes cases colorées.
Le résultat est une nouvelle matrice de **la même taille** que la matrice <code>Y</code> ou <code>X</code>, comme illustré dans la figure suivante.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%205/images/NumTwoMul.png" width="500">

Nous pouvons effectuer le produit élément par élément des tableaux <code>X</code> et <code>Y</code> comme suit :

In [ ]:
# Création du tableau Y

Y = np.array([[2, 1], [1, 2]])
Y

In [ ]:
# Création du tableau X

X = np.array([[1, 0], [0, 1]])
X

In [ ]:
# Multiplication de X par Y

Z = X * Y
Z

Il est également possible défectuer le produite *classique* de 2 matrices. (cf. [Produit matriciel sur Wikipédia](https://fr.wikipedia.org/wiki/Produit_matriciel))

On définit les matrices `A` et `B` :

In [ ]:
# Création de la matrice A

A = np.array([[0, 1, 1], [1, 0, 1]])
A

In [ ]:
# Création de la matrice B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

La fonction <code>np.dot</code> permet de réaliser le produit matriciel. A noter que ce produit n'est pas symétrique.

In [ ]:
# Calcul du produit matriciel de A par B

Z = np.dot(A,B)
Z

In [ ]:
# Calcul du produit matriciel de B par A

Z = np.dot(B,A)
Z

On peut obtenir la transposé d'une matrice avec l'attribut `T`.

In [ ]:
# Création d'une matrice C

C = np.array([[1,1],[2,2],[3,3]])
C

In [ ]:
# Transposé de C

C.T

## Quiz sur les tableaux à 2-dimension

Soit la liste `a` suivante, convertissez la en tableau numpy.

In [ ]:
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

# Ecrivez votre code ci-dessous

<details><summary>Cliquez ici pour voir la solution</summary>

```python
A = np.array(a)
A
```

</details>

Calculez le nombre d'élément dans le tableau que vous venez de créer.

In [ ]:
# Ecrivez votre code ci-dessous

<details><summary>Cliquez ici pour voir la solution</summary>

```python
A.size
```

</details>

Affichez le nombre de lignes et de colonnes de cette matrice.

In [ ]:
# Ecrivez votre code ci-dessous

<details><summary>Cliquez ici pour voir la solution</summary>

```python
A.shape
```

</details>

Renvoyer les éléments situés sur la première ligne et sur les 2 premières colonne.

In [ ]:
# Ecrivez votre code ci-dessous

<details><summary>Cliquez ici pour voir la solution</summary>

```python
A[0][0:2]
```

</details>

Calculer le produit matricielle de la matrice `A` avec la matrice `B` définit ci-dessous.

In [ ]:
B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

# Ecrivez votre code ci-dessous

<details><summary>Cliquez ici pour voir la solution</summary>

```python
X = np.dot(A,B)
X
```

</details>

#
<hr>

# Introduction à Pandas par la pratique: **Charger des données avec Pandas**

## **Objectifs**

Après avoir terminé cette partie, vous serez capable de :

* Utiliser **Pandas** pour accéder aux données et les visualiser

## A propos du Dataset

Le dataset fourni contient un ensemble de commandes de rpoduits. Le tableau contient une ligne pour chaque commande et plusieurs colonnes.

<ul>
    <li><b>OrderID</b> : Un identifiant unique pour chaque commande</li>
    <li><b>Product</b> : Le nom du produit acheté</li>
    <li><b>Category</b> : La catégorie à laquelle appartient le produit (par exemple, Électronique, Mobilier, Papeterie)</li>
    <li><b>Quantity</b> : Le nombre d’unités achetées pour ce produit</li>
    <li><b>Price</b> : Le prix unitaire du produit</li>
    <li><b>Total</b> : Le coût total du produit (calculé comme Quantity × Price)</li>
    <li><b>OrderDate</b> : La date à laquelle la commande a été passée</li>
    <li><b>CustomerCity</b> : La ville où réside le client</li>
</ul>

Vous pouvez consulter le jeu de données ici :


<font size="1">
<table style="font-size:medium; border:1px solid black; border-collapse:collapse;">
  <tr>
    <th>OrderID</th>
    <th>Product</th>
    <th>Category</th>
    <th>Quantity</th>
    <th>Price</th>
    <th>Total</th>
    <th>OrderDate</th>
    <th>CustomerCity</th>
  </tr>
  <tr>
    <td>1</td>
    <td>Laptop</td>
    <td>Electronics</td>
    <td>2</td>
    <td>800</td>
    <td>1600</td>
    <td>2022-01-10</td>
    <td>New York</td>
  </tr>
  <tr>
    <td>2</td>
    <td>Smartphone</td>
    <td>Electronics</td>
    <td>3</td>
    <td>600</td>
    <td>1800</td>
    <td>2022-02-15</td>
    <td>Los Angeles</td>
  </tr>
  <tr>
    <td>3</td>
    <td>Desk Chair</td>
    <td>Furniture</td>
    <td>5</td>
    <td>150</td>
    <td>750</td>
    <td>2022-03-12</td>
    <td>Chicago</td>
  </tr>
  <tr>
    <td>4</td>
    <td>Notebook</td>
    <td>Stationery</td>
    <td>10</td>
    <td>2</td>
    <td>20</td>
    <td>2022-04-05</td>
    <td>Houston</td>
  </tr>
  <tr>
    <td>5</td>
    <td>Monitor</td>
    <td>Electronics</td>
    <td>1</td>
    <td>300</td>
    <td>300</td>
    <td>2022-05-21</td>
    <td>Miami</td>
  </tr>
</table>
</font>

<hr>

## Introduction à <code>Pandas</code>

In [29]:
# Import required library

import pandas as pd

**Pandas** est une librairie qui utilise extensivement Numpy. Elle permet de manipuler des données tabulaires sous la forme d'un **dataframe**. Cette structure de données peut être décrite comme une matrice avec des noms de colonnes et de lignes.

Après la commande d’importation, nous avons désormais accès à un grand nombre de **classes et fonctions préconstruites**. Cela suppose que la bibliothèque est installée ; dans notre environnement de laboratoire, toutes les bibliothèques nécessaires sont déjà installées.

Une façon dont Pandas permet de travailler avec les données est via un **dataframe**. Voyons le processus pour passer d’un fichier de valeurs séparées par des virgules (<b>.csv</b>) à un dataframe.

La variable <code>csv_path</code> stocke le chemin du fichier <b>.csv</b>, qui est utilisé comme argument pour la fonction <code>read_csv</code>. Le résultat est stocké dans l’objet <code>df</code>, forme courte couramment utilisée pour une variable faisant référence à un dataframe Pandas.

In [ ]:
# Read data from CSV file
import pandas as pd

# csv_path = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/LXjSAttmoxJfEG6il1Bqfw/Product-sales.csv'
csv_path = 'Product-sales.csv'

df = pd.read_csv(csv_path)
print(df)

   OrderID     Product     Category  Quantity  Price  Total   OrderDate  \
0        1      Laptop  Electronics         2    800   1600  2022-01-10
1        2  Smartphone  Electronics         3    600   1800  2022-02-15
2        3  Desk Chair    Furniture         5    150    750  2022-03-12
3        4    Notebook   Stationery        10      2     20  2022-04-05
4        5     Monitor  Electronics         1    300    300  2022-05-21

  CustomerCity
0     New York
1  Los Angeles
2      Chicago
3      Houston
4        Miami

> Remarque : Cette version du sujet fonctionne en chargeant directement un fichier depuis son URL.
Lorsque vous travaillez sur la version téléchargée de ce notebook sur vos machines locales, vous pouvez simplement  préciser le chemin vers ce fichier dans la fonction `pandas.read_csv()`.

La méthode <code>head()</code> permet d'afficher les **cinq premières** lignes du dataframe :

In [34]:
# Afficher les 5 premières lignes du dataframe

df.head()

,OrderID,Product,Category,Quantity,Price,Total,OrderDate,CustomerCity
0,1,Laptop,Electronics,2,800,1600,2022-01-10,New York
1,2,Smartphone,Electronics,3,600,1800,2022-02-15,Los Angeles
2,3,Desk Chair,Furniture,5,150,750,2022-03-12,Chicago
3,4,Notebook,Stationery,10,2,20,2022-04-05,Houston
4,5,Monitor,Electronics,1,300,300,2022-05-21,Miami

<hr>

## Visualiser et accéder aux données

Vous pouvez également obtenir une colonne sous forme d'une **series**. Une **Series** est un tableau à 1 dimension avec un identifiant pour chaque élément.

On peut considérer une **Pandas Series** comme un dataframe à une dimension (1D). Il suffit d’utiliser **une seule paire de crochets** :

In [35]:
# Obtenir une série

x = df['Product']
x

0        Laptop
1    Smartphone
2    Desk Chair
3      Notebook
4       Monitor
Name: Product, dtype: str

Vous pouvez également obtenir une colonne sous forme de **dataframe**.

Par exemple, nous pouvons affecter la colonne <b>Quantity</b> :

In [ ]:
# Obtenir une colonne comme un dataframe

x = df[['Quantity']]
type(x)

L'image ci-dessous illustre bien l'accès à une colonne.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/CHIJ1eh6tYUzFsmgQIuCSA/1.PNG" width="1150">

Vous pouvez faire la même chose pour plusieurs colonnes; il suffit d’indiquer le nom du dataframe, ici <code>df</code>, et les noms des colonnes à récupérer **entre double crochets**.
Le résultat est un nouveau dataframe composé des colonnes spécifiées :

In [ ]:
# Access to multiple columns

y = df[['Product','Category', 'Quantity']]
y

La figure ci-dessous illustre cette sélection :

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/BiDzVOrMQbianIz9DMum7A/2.PNG" width="1100">

Une façon d’accéder aux éléments uniques est d’utiliser la méthode <code>iloc</code>, qui permet d’accéder à l'élement situé à la **Nième ligne** et  **Miène colonne** comme suit :

In [62]:
# Accès à la valeur de la première ligne et première colonne

df.iloc[0, 0]

np.int64(1)

L'image ci-dessous illustre différentes possibilités :

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/npw0rMu2hutg8MdOz4t_Kw/3.PNG" width="750">

On peut accéder aux éléments d'une colonne par le nom de la colonne en utilisant `loc`.

In [ ]:
# Accès au premier élément de la colonne 'Product'

df.loc[0, 'Product']

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/TR4-yEJdBj9NyQa5rlL6mg/4.PNG" width="750">

On peut également réaliser du slicing sur les dataframe, à la fois sur les indexes (en utilisant `iloc`) ou sur les noms des colonnes (en utilisant `loc`).

In [36]:
# Slicing d'un dataframe

df.iloc[0:2, 0:3]

   OrderID     Product     Category
0        1      Laptop  Electronics
1        2  Smartphone  Electronics

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/iyo_KV6ejpqgDxCcd3M1wg/5.PNG" width="950">

In [37]:
# Slicing d'un dataframe à partir des noms

df.loc[0:2, 'OrderID':'Category']

   OrderID     Product     Category
0        1      Laptop  Electronics
1        2  Smartphone  Electronics
2        3  Desk Chair    Furniture

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/88vCcZQ8N4W_R7WyKoqoAA/6.PNG" width="750">

<hr>

## Quiz sur les DataFrame

Définissez la variable <code>q</code> et affectez lui la colonne <b>Price</b> comme un dataframe

In [54]:
# Le dataframe doit avoir été chargé dans une cellul précédente.

# Ecrire le code ci-dessous
q = df[["Price"]]
print(q)

   Price
0    800
1    600
2    150
3      2
4    300

<details><summary>Cliquez ici pour voir la solution</summary>

```python
q = df[['Price']]
q
    
```

</details>

Affectez à la variable <code>q</code> le dataframe composé des colonnes <b>Product</b> et <b>Category</b> :

In [55]:
# Ecrire le code ci-dessous
q = df[["Product", "Category"]]
print(q)

      Product     Category
0      Laptop  Electronics
1  Smartphone  Electronics
2  Desk Chair    Furniture
3    Notebook   Stationery
4     Monitor  Electronics

<details><summary>Cliquez ici pour voir la solution</summary>

```python
q = df[['Product', 'Category']]
q
    
```

</details>

Affichez l'élément situé sur la 2eme ligne et 3eme colonne du dataframe `df` :

In [61]:
# Ecrire le code ci-dessous
print(df.iloc[1:3, 2])

1    Electronics
2      Furniture
Name: Category, dtype: str

<details><summary>Cliquez ici pour voir la solution</summary>

```python
df.iloc[1, 2]
    
```

</details>

Utilisez la liste suivante pour convertir l’index du dataframe <code>df</code> en caractères et l’affecter à <code>df_new</code>. Pour cela affectez la valeur de la liste new_index à l'attribut `index` du dataframe.

Trouvez l’élément correspondant à l’index de ligne <code>a</code> et à la colonne <code>'CustomerCity'</code>. Ensuite, sélectionnez les lignes <code>a</code> à <code>d</code> pour la colonne <code>'CustomerCity'</code>.

In [ ]:
new_index=['a','b','c','d','e']

# Ecrire le code ci-dessous

<details><summary>Cliquez ici pour voir la solution</summary>

```python
df_new=df
df_new.index=new_index
df_new.loc['a', 'CustomerCity']
df_new.loc['a':'d', 'CustomerCity']
    
```

</details>